title: Dd:Dd

url: 'https://super-dev.xyz'
ga_stream_id: G-JQ9TZ4W7KK

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty

sass:
  sass_dir: static/css/partial
  style: compressed


theme:
  color: black
